"""
Curated database of towns within ~1 hour commute to NYC (Midtown Manhattan).

Data sources for verification:
- Commute times: NJ Transit, Metro-North, LIRR schedules
- School ratings: GreatSchools.org (1-10 scale)
- Property tax rates: NJ Division of Taxation, NY State tax records
- Median home prices: Zillow, Redfin market data

NOTE: All values are approximate and should be verified with current listings.
Last curated: 2026-03. Prices and tax rates change frequently.
"""

# Each town entry:
# {
#   "name": str,
#   "state": str,
#   "county": str,
#   "commute_minutes": int (to Midtown Manhattan via train),
#   "transit_line": str,
#   "median_home_price": int,
#   "price_range_low": int,  # typical range for 3-4 BR homes
#   "price_range_high": int,
#   "avg_property_tax": int (annual, for median-priced home),
#   "tax_rate_pct": float (effective tax rate),
#   "elementary_school_rating": float (GreatSchools avg),
#   "middle_school_rating": float,
#   "high_school_rating": float,
#   "avg_school_rating": float,
#   "notable_schools": list[str],
#   "highlights": list[str],
# }

TOWNS = [
    # === NEW JERSEY (NJ Transit / PATH) ===
    {
        "name": "Summit",
        "state": "NJ",
        "county": "Union",
        "commute_minutes": 47,
        "transit_line": "NJ Transit Midtown Direct",
        "median_home_price": 1_050_000,
        "price_range_low": 700_000,
        "price_range_high": 1_800_000,
        "avg_property_tax": 22_000,
        "tax_rate_pct": 2.10,
        "elementary_school_rating": 9,
        "middle_school_rating": 8,
        "high_school_rating": 9,
        "avg_school_rating": 8.7,
        "notable_schools": ["Franklin Elementary", "Summit High School"],
        "highlights": [
            "Walkable downtown with shops and restaurants",
            "Direct train to Penn Station (47 min)",
            "Excellent school district consistently ranked top in NJ",
        ],
    },
    {
        "name": "Maplewood",
        "state": "NJ",
        "county": "Essex",
        "commute_minutes": 42,
        "transit_line": "NJ Transit Midtown Direct",
        "median_home_price": 750_000,
        "price_range_low": 500_000,
        "price_range_high": 1_400_000,
        "avg_property_tax": 19_500,
        "tax_rate_pct": 2.60,
        "elementary_school_rating": 8,
        "middle_school_rating": 7,
        "high_school_rating": 8,
        "avg_school_rating": 7.7,
        "notable_schools": ["Seth Boyden Elementary", "Columbia High School"],
        "highlights": [
            "Diverse, artsy community",
            "Direct train to Penn Station (42 min)",
            "Village center with local restaurants and shops",
        ],
    },
    {
        "name": "South Orange",
        "state": "NJ",
        "county": "Essex",
        "commute_minutes": 40,
        "transit_line": "NJ Transit Midtown Direct",
        "median_home_price": 700_000,
        "price_range_low": 450_000,
        "price_range_high": 1_300_000,
        "avg_property_tax": 18_000,
        "tax_rate_pct": 2.57,
        "elementary_school_rating": 7,
        "middle_school_rating": 7,
        "high_school_rating": 8,
        "avg_school_rating": 7.3,
        "notable_schools": ["Marshall Elementary", "Columbia High School (shared w/ Maplewood)"],
        "highlights": [
            "Shares top-rated Columbia HS with Maplewood",
            "Seton Hall University campus",
            "Quick Midtown Direct service",
        ],
    },
    {
        "name": "Glen Ridge",
        "state": "NJ",
        "county": "Essex",
        "commute_minutes": 40,
        "transit_line": "NJ Transit Midtown Direct",
        "median_home_price": 850_000,
        "price_range_low": 600_000,
        "price_range_high": 1_500_000,
        "avg_property_tax": 20_000,
        "tax_rate_pct": 2.35,
        "elementary_school_rating": 9,
        "middle_school_rating": 8,
        "high_school_rating": 9,
        "avg_school_rating": 8.7,
        "notable_schools": ["Forest Avenue School", "Glen Ridge High School"],
        "highlights": [
            "Small-town charm, gas-lit streets",
            "Top-rated schools for its size",
            "Direct train to Penn Station",
        ],
    },
    {
        "name": "Montclair",
        "state": "NJ",
        "county": "Essex",
        "commute_minutes": 45,
        "transit_line": "NJ Transit Midtown Direct",
        "median_home_price": 900_000,
        "price_range_low": 500_000,
        "price_range_high": 1_900_000,
        "avg_property_tax": 21_000,
        "tax_rate_pct": 2.33,
        "elementary_school_rating": 7,
        "middle_school_rating": 7,
        "high_school_rating": 8,
        "avg_school_rating": 7.3,
        "notable_schools": ["Watchung School", "Montclair High School"],
        "highlights": [
            "Vibrant arts and dining scene",
            "Diverse community",
            "Multiple train stations",
        ],
    },
    {
        "name": "New Providence",
        "state": "NJ",
        "county": "Union",
        "commute_minutes": 55,
        "transit_line": "NJ Transit Gladstone Branch",
        "median_home_price": 750_000,
        "price_range_low": 500_000,
        "price_range_high": 1_200_000,
        "avg_property_tax": 15_500,
        "tax_rate_pct": 2.07,
        "elementary_school_rating": 8,
        "middle_school_rating": 8,
        "high_school_rating": 8,
        "avg_school_rating": 8.0,
        "notable_schools": ["Allen W. Roberts School", "New Providence High School"],
        "highlights": [
            "Lower taxes than neighboring Summit and Chatham",
            "Strong schools at a more affordable price point",
            "Murray Hill station on NJ Transit Gladstone Branch",
        ],
    },
    {
        "name": "Chatham",
        "state": "NJ",
        "county": "Morris",
        "commute_minutes": 50,
        "transit_line": "NJ Transit Midtown Direct",
        "median_home_price": 1_100_000,
        "price_range_low": 750_000,
        "price_range_high": 1_800_000,
        "avg_property_tax": 20_000,
        "tax_rate_pct": 1.82,
        "elementary_school_rating": 9,
        "middle_school_rating": 9,
        "high_school_rating": 9,
        "avg_school_rating": 9.0,
        "notable_schools": ["Lafayette Avenue School", "Chatham High School"],
        "highlights": [
            "One of NJ's top-rated school districts",
            "Charming downtown",
            "Midtown Direct express service",
        ],
    },
    {
        "name": "Madison",
        "state": "NJ",
        "county": "Morris",
        "commute_minutes": 55,
        "transit_line": "NJ Transit Midtown Direct",
        "median_home_price": 900_000,
        "price_range_low": 600_000,
        "price_range_high": 1_600_000,
        "avg_property_tax": 18_500,
        "tax_rate_pct": 2.06,
        "elementary_school_rating": 8,
        "middle_school_rating": 8,
        "high_school_rating": 9,
        "avg_school_rating": 8.3,
        "notable_schools": ["Kings Road School", "Madison High School"],
        "highlights": [
            "Drew University campus, college-town feel",
            "Walkable downtown with restaurants",
            "Strong schools",
        ],
    },
    {
        "name": "Westfield",
        "state": "NJ",
        "county": "Union",
        "commute_minutes": 55,
        "transit_line": "NJ Transit Raritan Valley Line",
        "median_home_price": 1_000_000,
        "price_range_low": 650_000,
        "price_range_high": 1_900_000,
        "avg_property_tax": 22_000,
        "tax_rate_pct": 2.20,
        "elementary_school_rating": 8,
        "middle_school_rating": 8,
        "high_school_rating": 9,
        "avg_school_rating": 8.3,
        "notable_schools": ["Franklin Elementary", "Westfield High School"],
        "highlights": [
            "Vibrant downtown shopping district",
            "Highly regarded schools",
            "Strong community programs",
        ],
    },
    {
        "name": "Cranford",
        "state": "NJ",
        "county": "Union",
        "commute_minutes": 50,
        "transit_line": "NJ Transit Raritan Valley Line",
        "median_home_price": 700_000,
        "price_range_low": 475_000,
        "price_range_high": 1_200_000,
        "avg_property_tax": 16_000,
        "tax_rate_pct": 2.29,
        "elementary_school_rating": 8,
        "middle_school_rating": 7,
        "high_school_rating": 8,
        "avg_school_rating": 7.7,
        "notable_schools": ["Brookside Place School", "Cranford High School"],
        "highlights": [
            "Affordable relative to neighbors",
            "Charming downtown along the Rahway River",
            "Good value for school quality",
        ],
    },
    {
        "name": "Ridgewood",
        "state": "NJ",
        "county": "Bergen",
        "commute_minutes": 50,
        "transit_line": "NJ Transit Main/Bergen Line",
        "median_home_price": 1_050_000,
        "price_range_low": 700_000,
        "price_range_high": 1_900_000,
        "avg_property_tax": 24_000,
        "tax_rate_pct": 2.29,
        "elementary_school_rating": 9,
        "middle_school_rating": 9,
        "high_school_rating": 9,
        "avg_school_rating": 9.0,
        "notable_schools": ["Travell Elementary", "Ridgewood High School"],
        "highlights": [
            "Top-tier school district",
            "Upscale downtown village",
            "Strong property values",
        ],
    },
    {
        "name": "Glen Rock",
        "state": "NJ",
        "county": "Bergen",
        "commute_minutes": 45,
        "transit_line": "NJ Transit Main/Bergen Line",
        "median_home_price": 800_000,
        "price_range_low": 550_000,
        "price_range_high": 1_300_000,
        "avg_property_tax": 18_000,
        "tax_rate_pct": 2.25,
        "elementary_school_rating": 9,
        "middle_school_rating": 8,
        "high_school_rating": 9,
        "avg_school_rating": 8.7,
        "notable_schools": ["Byrd Elementary", "Glen Rock High School"],
        "highlights": [
            "Excellent schools, quieter than Ridgewood",
            "Lower prices than neighboring Ridgewood",
            "Family-friendly community",
        ],
    },
    {
        "name": "Millburn",
        "state": "NJ",
        "county": "Essex",
        "commute_minutes": 38,
        "transit_line": "NJ Transit Midtown Direct",
        "median_home_price": 1_500_000,
        "price_range_low": 900_000,
        "price_range_high": 2_000_000,
        "avg_property_tax": 28_000,
        "tax_rate_pct": 1.87,
        "elementary_school_rating": 10,
        "middle_school_rating": 9,
        "high_school_rating": 10,
        "avg_school_rating": 9.7,
        "notable_schools": ["Wyoming Elementary", "Millburn High School"],
        "highlights": [
            "Consistently ranked #1 school district in NJ",
            "Short Hills Mall area",
            "Fastest Midtown Direct commute",
        ],
    },
    {
        "name": "Morristown",
        "state": "NJ",
        "county": "Morris",
        "commute_minutes": 55,
        "transit_line": "NJ Transit Midtown Direct",
        "median_home_price": 750_000,
        "price_range_low": 450_000,
        "price_range_high": 1_400_000,
        "avg_property_tax": 16_500,
        "tax_rate_pct": 2.20,
        "elementary_school_rating": 7,
        "middle_school_rating": 7,
        "high_school_rating": 7,
        "avg_school_rating": 7.0,
        "notable_schools": ["Alexander Hamilton School", "Morristown High School"],
        "highlights": [
            "Lively downtown with nightlife and dining",
            "Historic town (Washington's headquarters)",
            "More affordable entry point",
        ],
    },
    # === NEW YORK (Metro-North / LIRR) ===
    {
        "name": "Scarsdale",
        "state": "NY",
        "county": "Westchester",
        "commute_minutes": 37,
        "transit_line": "Metro-North Harlem Line",
        "median_home_price": 1_800_000,
        "price_range_low": 1_200_000,
        "price_range_high": 2_000_000,
        "avg_property_tax": 28_000,
        "tax_rate_pct": 1.56,
        "elementary_school_rating": 10,
        "middle_school_rating": 10,
        "high_school_rating": 10,
        "avg_school_rating": 10.0,
        "notable_schools": ["Edgewood School", "Scarsdale High School"],
        "highlights": [
            "Premier school district in Westchester",
            "Quick Metro-North to Grand Central",
            "High price floor but exceptional schools",
        ],
    },
    {
        "name": "Bronxville",
        "state": "NY",
        "county": "Westchester",
        "commute_minutes": 30,
        "transit_line": "Metro-North Harlem Line",
        "median_home_price": 1_700_000,
        "price_range_low": 1_000_000,
        "price_range_high": 2_000_000,
        "avg_property_tax": 25_000,
        "tax_rate_pct": 1.47,
        "elementary_school_rating": 10,
        "middle_school_rating": 9,
        "high_school_rating": 10,
        "avg_school_rating": 9.7,
        "notable_schools": ["Bronxville Elementary", "Bronxville High School"],
        "highlights": [
            "One of the shortest commutes to GCT",
            "Compact, walkable village",
            "Exceptional schools",
        ],
    },
    {
        "name": "Pelham",
        "state": "NY",
        "county": "Westchester",
        "commute_minutes": 33,
        "transit_line": "Metro-North New Haven Line",
        "median_home_price": 950_000,
        "price_range_low": 650_000,
        "price_range_high": 1_600_000,
        "avg_property_tax": 20_000,
        "tax_rate_pct": 2.11,
        "elementary_school_rating": 8,
        "middle_school_rating": 8,
        "high_school_rating": 8,
        "avg_school_rating": 8.0,
        "notable_schools": ["Prospect Hill Elementary", "Pelham Memorial High School"],
        "highlights": [
            "More affordable Westchester option",
            "Close to NYC, quick commute",
            "Good schools at lower price point",
        ],
    },
    {
        "name": "Larchmont",
        "state": "NY",
        "county": "Westchester",
        "commute_minutes": 35,
        "transit_line": "Metro-North New Haven Line",
        "median_home_price": 1_400_000,
        "price_range_low": 900_000,
        "price_range_high": 2_000_000,
        "avg_property_tax": 24_000,
        "tax_rate_pct": 1.71,
        "elementary_school_rating": 9,
        "middle_school_rating": 9,
        "high_school_rating": 9,
        "avg_school_rating": 9.0,
        "notable_schools": ["Chatsworth Avenue School", "Mamaroneck High School"],
        "highlights": [
            "Waterfront community on Long Island Sound",
            "Shares excellent Mamaroneck school district",
            "Charming village center",
        ],
    },
    {
        "name": "Hastings-on-Hudson",
        "state": "NY",
        "county": "Westchester",
        "commute_minutes": 40,
        "transit_line": "Metro-North Hudson Line",
        "median_home_price": 850_000,
        "price_range_low": 600_000,
        "price_range_high": 1_400_000,
        "avg_property_tax": 19_000,
        "tax_rate_pct": 2.24,
        "elementary_school_rating": 8,
        "middle_school_rating": 8,
        "high_school_rating": 8,
        "avg_school_rating": 8.0,
        "notable_schools": ["Hillside Elementary", "Hastings High School"],
        "highlights": [
            "Scenic Hudson River views",
            "Artsy, progressive community",
            "Good value in Westchester",
        ],
    },
    {
        "name": "Irvington",
        "state": "NY",
        "county": "Westchester",
        "commute_minutes": 42,
        "transit_line": "Metro-North Hudson Line",
        "median_home_price": 1_000_000,
        "price_range_low": 700_000,
        "price_range_high": 1_700_000,
        "avg_property_tax": 22_000,
        "tax_rate_pct": 2.20,
        "elementary_school_rating": 9,
        "middle_school_rating": 8,
        "high_school_rating": 9,
        "avg_school_rating": 8.7,
        "notable_schools": ["Main Street School", "Irvington High School"],
        "highlights": [
            "Scenic Hudson River village",
            "Strong school district",
            "Historic estates and parks",
        ],
    },
    {
        "name": "Chappaqua",
        "state": "NY",
        "county": "Westchester",
        "commute_minutes": 55,
        "transit_line": "Metro-North Harlem Line",
        "median_home_price": 1_100_000,
        "price_range_low": 750_000,
        "price_range_high": 1_800_000,
        "avg_property_tax": 26_000,
        "tax_rate_pct": 2.36,
        "elementary_school_rating": 9,
        "middle_school_rating": 9,
        "high_school_rating": 10,
        "avg_school_rating": 9.3,
        "notable_schools": ["Westorchard Elementary", "Horace Greeley High School"],
        "highlights": [
            "Top-rated Chappaqua Central School District",
            "Rural/suburban feel",
            "Horace Greeley HS is nationally ranked",
        ],
    },
    # === LONG ISLAND (LIRR) ===
    {
        "name": "Garden City",
        "state": "NY",
        "county": "Nassau",
        "commute_minutes": 40,
        "transit_line": "LIRR Hempstead Branch",
        "median_home_price": 1_100_000,
        "price_range_low": 750_000,
        "price_range_high": 1_800_000,
        "avg_property_tax": 22_000,
        "tax_rate_pct": 2.00,
        "elementary_school_rating": 9,
        "middle_school_rating": 9,
        "high_school_rating": 9,
        "avg_school_rating": 9.0,
        "notable_schools": ["Stewart School", "Garden City High School"],
        "highlights": [
            "Planned community with wide streets",
            "Roosevelt Field Mall nearby",
            "Consistently top-rated LI school district",
        ],
    },
    {
        "name": "Manhasset",
        "state": "NY",
        "county": "Nassau",
        "commute_minutes": 35,
        "transit_line": "LIRR Port Washington Branch",
        "median_home_price": 1_600_000,
        "price_range_low": 1_000_000,
        "price_range_high": 2_000_000,
        "avg_property_tax": 24_000,
        "tax_rate_pct": 1.50,
        "elementary_school_rating": 9,
        "middle_school_rating": 9,
        "high_school_rating": 10,
        "avg_school_rating": 9.3,
        "notable_schools": ["Munsey Park Elementary", "Manhasset High School"],
        "highlights": [
            "Americana Manhasset (luxury shopping)",
            "Short LIRR ride to Penn Station",
            "Blue-ribbon school district",
        ],
    },
    {
        "name": "Port Washington",
        "state": "NY",
        "county": "Nassau",
        "commute_minutes": 40,
        "transit_line": "LIRR Port Washington Branch",
        "median_home_price": 1_200_000,
        "price_range_low": 800_000,
        "price_range_high": 1_900_000,
        "avg_property_tax": 22_000,
        "tax_rate_pct": 1.83,
        "elementary_school_rating": 8,
        "middle_school_rating": 8,
        "high_school_rating": 9,
        "avg_school_rating": 8.3,
        "notable_schools": ["Sousa Elementary", "Schreiber High School"],
        "highlights": [
            "Waterfront community with harbor views",
            "End of LIRR Port Washington branch (seat guaranteed)",
            "Mix of housing types and price points",
        ],
    },
    {
        "name": "Great Neck",
        "state": "NY",
        "county": "Nassau",
        "commute_minutes": 33,
        "transit_line": "LIRR Port Washington Branch",
        "median_home_price": 1_400_000,
        "price_range_low": 900_000,
        "price_range_high": 2_000_000,
        "avg_property_tax": 22_000,
        "tax_rate_pct": 1.57,
        "elementary_school_rating": 9,
        "middle_school_rating": 9,
        "high_school_rating": 10,
        "avg_school_rating": 9.3,
        "notable_schools": ["Lakeville Elementary", "Great Neck South High School"],
        "highlights": [
            "One of the shortest LIRR commutes",
            "Nationally ranked school district",
            "Diverse, walkable community",
        ],
    },
    # === CONNECTICUT (Metro-North) ===
    {
        "name": "Darien",
        "state": "CT",
        "county": "Fairfield",
        "commute_minutes": 55,
        "transit_line": "Metro-North New Haven Line",
        "median_home_price": 1_800_000,
        "price_range_low": 1_200_000,
        "price_range_high": 2_000_000,
        "avg_property_tax": 22_000,
        "tax_rate_pct": 1.22,
        "elementary_school_rating": 10,
        "middle_school_rating": 9,
        "high_school_rating": 10,
        "avg_school_rating": 9.7,
        "notable_schools": ["Hindley Elementary", "Darien High School"],
        "highlights": [
            "Lower property tax rate than NJ/NY",
            "No state income tax on wages (CT has income tax, but lower than NY/NJ)",
            "Beach access, affluent community",
        ],
    },
    {
        "name": "Stamford (North Stamford)",
        "state": "CT",
        "county": "Fairfield",
        "commute_minutes": 50,
        "transit_line": "Metro-North New Haven Line (express)",
        "median_home_price": 800_000,
        "price_range_low": 500_000,
        "price_range_high": 1_500_000,
        "avg_property_tax": 14_000,
        "tax_rate_pct": 1.75,
        "elementary_school_rating": 7,
        "middle_school_rating": 7,
        "high_school_rating": 7,
        "avg_school_rating": 7.0,
        "notable_schools": ["Newfield Elementary", "Stamford High School"],
        "highlights": [
            "Express train to Grand Central (50 min)",
            "Lower taxes than Westchester/NJ",
            "Urban amenities within Stamford itself",
        ],
    },
    {
        "name": "Norwalk (East Norwalk/Rowayton)",
        "state": "CT",
        "county": "Fairfield",
        "commute_minutes": 58,
        "transit_line": "Metro-North New Haven Line",
        "median_home_price": 750_000,
        "price_range_low": 500_000,
        "price_range_high": 1_400_000,
        "avg_property_tax": 13_000,
        "tax_rate_pct": 1.73,
        "elementary_school_rating": 7,
        "middle_school_rating": 7,
        "high_school_rating": 7,
        "avg_school_rating": 7.0,
        "notable_schools": ["Rowayton Elementary", "Brien McMahon High School"],
        "highlights": [
            "Rowayton neighborhood is charming coastal village",
            "Lowest property taxes on this list",
            "Affordable CT option with beach access",
        ],
    },
]
